export enum ApplicationPage {
  HOME,
  TUTORIALS,
  TUTORIALS_CREATE_ACCOUNT,
  TUTORIALS_RECEIVE_PAYMENTS,
  TUTORIALS_MONITOR_PAYMENTS,
  TUTORIALS_WITHDRAW,
  TUTORIALS_SHARE_ACCESS,
  TUTORIALS_PAYMENT_SETTINGS,
  TUTORIALS_NOTIFICATIONS,
  TUTORIALS_API,
  RESOURCES,
  RESOURCES_CURRENCIES,
  RESOURCES_BLOCKCHAINS,
  RESOURCES_TOKENS,
  RESOURCES_CONTRACTS
}
