import * as jwt from 'jsonwebtoken'

export const RANGO_PROXY_PREFIX = '/rango'
export const MAX_QUERY_PARAM_LENGTH = 200
export const BLOCKCHAIN_BTC = 'btc'
export const BLOCKCHAIN_BTC_NATIVE_TOKEN_SYMBOL = 'BTC'
export const BLOCKCHAIN_BTC_NATIVE_TOKEN_DECIMALS = 8
export const JWT_ALGORITHM: jwt.Algorithm = 'HS256'
export const META_SAVING_SAMPLING_SECONDS = 600
export const EXCHANGE_RATE_SAVING_SAMPLING_SECONDS = 3600
export const DEFAULT_FIAT_DECIMAL_PLACES = 4
export const PAYMENT_ID_MAX_LENGTH = 100
export const CURRENCY_MAX_LENGTH = 3
export const LANGUAGE_MAX_LENGTH = 2
export const BLOCKCHAIN_MAX_LENGTH = 100
export const EMAIL_MAX_LENGTH = 100
export const DESC_MAX_LENGTH = 1000
export const ADDRESS_MAX_LENGTH = 100
export const TRANSACTION_MAX_LENGTH = 100
export const TICKET_TYPE_MAX_LENGTH = 100
export const TOKEN_MAX_LENGTH = 100
export const CALLBACK_URL_MAX_LENGTH = 1000
export const SECRET_KEY_MAX_LENGTH = 100
export const DEFAULT_MAX_LENGTH = 100
export const MAX_NOTIFICATION_TIMESTAMP_DELTA_SEC = 3600
export const CURRENCY_USD = 'usd'
export const COMMON_SETTINGS_DEFAULT_CURRENCY = CURRENCY_USD

// caching
export const DEFAULT_RANGO_CACHING_SECONDS = 600
export const DEFAULT_EXCHANGERATE_CACHING_SECONDS = 3600
export const DEFAULT_ROUTE_PAYMENT_CACHING_SECONDS = 10
export const DEFAULT_ROUTE_ACCOUNT_PAYMENT_CACHING_SECONDS = 10
export const DEFAULT_ROUTE_API_CACHING_SECONDS = 10
export const DEFAULT_ROUTE_ACCOUNT_DOC_CACHING_SECONDS = 3600

// tasks
export const PAYMENT_TASK_INTERVAL_SECONDS = 10
export const NOTIFICATION_TASK_INTERVAL_SECONDS = 10
export const META_TASK_INTERVAL_SECONDS = DEFAULT_RANGO_CACHING_SECONDS

// api
export const API_THROTTLING_INTERVAL_SECONDS = 60
export const API_MAX_CALLS_PER_THROTTLING_INTERVAL_SECONDS = 60

// settings
export const APP_SETTINGS_PREFIX = 'app'
export const BLOCKCHAIN_SETTINGS_PREFIX = 'blockchain'
export const TOKEN_SETTINGS_PREFIX = 'token'
export const DEFAULT_ACCOUNT_PAYMENT_SETTINGS_PREFIX = 'account_default_payment'
export const BLOCKCHAIN_EVM_CLIENT_CONFIG_SETTINGS_PREFIX = 'blockchain_evm_client_config'
export const PERMISSION_PRIORITY = { 'Disable': 0, 'View': 1, 'Modify': 2 }
export const COMMON_SETTINGS_MAX_DESCRIPTION_LENGTH = 250
